// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUkKLApIpw9FwN0JQur_CWdGh5nYFnx_s',
    appId: '1:891387863088:web:74df89660490c02045cdf5',
    messagingSenderId: '891387863088',
    projectId: 'we-attendance-112f7',
    authDomain: 'we-attendance-112f7.firebaseapp.com',
    storageBucket: 'we-attendance-112f7.appspot.com',
    measurementId: 'G-N20MVM6P6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZaRXOvei0SGg_t6B0tPD38l-b8G7Y9nA',
    appId: '1:891387863088:android:7771566853941dd145cdf5',
    messagingSenderId: '891387863088',
    projectId: 'we-attendance-112f7',
    storageBucket: 'we-attendance-112f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG18pTrR-DaMD7rZ2lrr8JnCNvaSU41Eg',
    appId: '1:891387863088:ios:36426fd8f59118c145cdf5',
    messagingSenderId: '891387863088',
    projectId: 'we-attendance-112f7',
    storageBucket: 'we-attendance-112f7.appspot.com',
    iosBundleId: 'com.example.hrWeAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG18pTrR-DaMD7rZ2lrr8JnCNvaSU41Eg',
    appId: '1:891387863088:ios:470b148f4121f8d545cdf5',
    messagingSenderId: '891387863088',
    projectId: 'we-attendance-112f7',
    storageBucket: 'we-attendance-112f7.appspot.com',
    iosBundleId: 'com.example.hrWeAttendance.RunnerTests',
  );
}
