import 'package:get/get.dart';

class LocalString extends Translations
{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      'fieldstafftrackingsystem':'Field Staff Tracking System',
      'login':'LOGIN',
      'username':'Username',
      'pleaseenterusername':'Please Enter Username',
      'password':'Password',
      'pleaseenterpassword':'Please Enter Password',
      'forgotpassword':'Forgot Password',
      'technicalsupport':'Technical Support',
      'alert':'Alert',
      'please_wait': 'Please Wait',
      'success':'Success',
      'login_success':'Login Successfully',
      'please_check_internet':'Please Check Your Internet',
      //Newwwwwwwwwwwwww
      'profile': 'Profile',
      'hr_staff_attendance': 'Staff Attendance',
      'leave_request': 'Leave Request',
      'change_language': 'Change Language',
      'change_password': 'Change Password',
      'logout': 'Logout',
      'are_you_sure_want_to': 'Are you sure want to',
      'yes': 'Yes',
      'no': 'No',
      'gujarati': 'Gujarati',
      'english': 'English',
      'marathi': 'Marathi',
      'hindi': 'Hindi',
      'choose_site': 'Choose Your Site',
      'choose_sub_site': 'Choose Your Sub Site',
      'punch_out_anywhere': 'Punch out from anywhere',
      'please': 'Please',
      'punch' : 'Punch',
      'in': 'In',
      'out': 'Out',
      'attendance': 'Attendance',
      'already_done': 'Already Done',
      'next': 'Next',
      'or': 'Or',
      'after': 'After',
      'hrs_left': 'Hrs Left',
      'ok': 'Ok',
      'successfully': 'Successfully',
      'sorry': 'Sorry',
      'you_are_in_site': 'You are in site',
      'you_are_not_in_site': 'You are not in site',
      'please_go_to_your_site': 'Please Go To Your Site',
      'time': 'Time',
      'working_hrs': '"Working Hrs',
      'no_internet_connection': 'No Internet Connection',
      'home': 'Home',
      'map': 'Map',
      'report': 'Report',
      'leave': 'Leave',
      'track': 'Track',
      'problems': 'Problems',
      'problem': 'Problem',
      'its_take_a_time_while_loading_map': "It's take a time while loading map",
      'notifications': 'Notifications',
      'record_not_found': 'Record Not Found',
      'present': 'Present',
      'absent': 'Absent',
      'total': 'Total',
      'monthly': 'Monthly',
      'numb': 'No',
      'type': 'Type',
      'working_hours': 'Working Hours',
      'my': 'My',
      'quota': 'Quota',
      'used': 'Used',
      'available': 'Available',
      'add': 'Add',
      'choose': 'Choose',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'reason': 'Reason',
      'take_photo': 'Take Photo',
      'submit': 'Submit',
      'fill': 'Fill',
      'days': 'Days',
      'remark': 'Remark',
      'reset': 'Reset',
      'enter_the_old_password_desc': 'Enter the old password with your account and verify \nold password to reset your password',
      'old': 'Old',
      'new': 'New',
      'confirm': 'Confirm',
      'enter_the': 'Enter The',
      'once_you_start': 'Once you start a new',
      'you_ll': "You'll",
      'see_it_listen_here': 'see it listed here',
      'to': 'To',
      'delete': 'Delete',
      'this': 'This',
      'edit': 'Edit',
      'is': 'Is',
      'finished': 'Finished',
      'please_select_valid_date': 'Please Select Valid Date',
      'max': 'Max',
      'select': 'Select',
      'save': 'Save',
      'updated': 'Updated',
      'you_can_not': "You can not delete today's problem",
      'first': 'First',
      'enter': 'Enter',
      'character': 'Character',
      'right': 'Right',
      'same_as': 'Same as',
      'your_password_changed': 'Your Password Change Successfully',
      'staff': 'Staff',
      'overall': 'Overall',
      'no_data_found': 'No data found',
      'of': 'of',
      'site': 'Site',
      'sites': 'Sites',
      'pending': 'Pending',
      'accept': 'Accept',
      'reject': 'Reject',
      'data_not_available': 'Data Not Available',
      'name': 'Name',
      'apply_date': 'Apply Date',
      'sub': 'Sub',
      'details': 'Details',
      'why': 'Why',
      'already': 'Already',
      'accepted': 'Accepted',
      'rejected': 'Rejected',
      'status': 'Status',
      'update': 'Update',
      'tracking': 'Tracking',
    },
    'mr_IN':{
      'fieldstafftrackingsystem':'फील्ड स्टाफ ट्रॅकिंग सिस्टम',
      'login':'लॉगिन',
      'username':'वापरकर्तानाव',
      'pleaseenterusername':'कृपया वापरकर्तानाव प्रविष्ट करा',
      'password':'पासवर्ड',
      'pleaseenterpassword':'कृपया पासवर्ड टाका',
      'forgotpassword':'पासवर्ड विसरलात',
      'technicalsupport':'तांत्रिक सहाय्य',
      'alert':'इशारा',
      'please_wait': 'कृपया थांबा',
      'success':'यश',
      'login_success':'यशस्वीरित्या लॉगिन करा',
      'please_check_internet':'कृपया तुमचे इंटरनेट तपासा',
      'profile': 'प्रोफाइल',
      'hr_staff_attendance': 'कर्मचारी उपस्थिती',
      'leave_request': 'विनंती सोडा',
      'change_language': 'भाषा बदला',
      'change_password': 'पासवर्ड बदला',
      'logout': 'बाहेर पडणे',
      'are_you_sure_want_to': 'तुम्हाला नक्की करायचे आहे',
      'yes': 'होय',
      'no': 'नाही',
      'gujarati': 'गुजराती',
      'english': 'इंग्रजी',
      'marathi': 'मराठी',
      'hindi': 'हिंदी',
      'choose_site': 'तुमची साइट निवडा',
      'choose_sub_site': 'तुमची उप साइट निवडा',
      'punch_out_anywhere': 'कोठूनही पंच बाहेर',
      'please': 'कृपया',
      'punch' : 'पंच',
      'in': 'मध्ये',
      'out': 'बाहेर',
      'attendance': 'उपस्थिती',
      'already_done': 'आधीच झाले',
      'next': 'पुढे',
      'or': 'किंवा',
      'after': 'नंतर',
      'hrs_left': 'तास बाकी',
      'ok': 'ठीक आहे',
      'successfully': 'यशस्वीपणे',
      'sorry': 'क्षमस्व',
      'you_are_in_site': 'तुम्ही साइटवर आहात',
      'you_are_not_in_site': 'तुम्ही साइटवर नाही आहात',
      'please_go_to_your_site': 'कृपया तुमच्या साइटवर जा',
      'time': 'वेळ',
      'working_hrs': 'कामाचे तास',
      'no_internet_connection': 'इंटरनेट कनेक्शन नाही',
      'home': 'मुख्यपृष्ठ',
      'map': 'नकाशा',
      'report': 'अहवाल द्या',
      'leave': 'सोडा',
      'track': 'ट्रॅक',
      'problems': 'अडचणी',
      'problem': 'अडचणी',
      'its_take_a_time_while_loading_map': "नकाशा लोड करताना थोडा वेळ लागतो",
      'notifications': 'अधिसूचना',
      'record_not_found': 'रेकॉर्ड सापडला नाही',
      'present': 'उपस्थित',
      'absent': 'अनुपस्थित',
      'total': 'एकूण',
      'monthly': 'मासिक',
      'numb': 'संख्या',
      'type': 'प्रकार',
      'working_hours': 'कामाचे तास',
      'my': 'माझे',
      'quota': 'कोटा',
      'used': 'वापरले',
      'available': 'उपलब्ध',
      'add': 'जोडा',
      'choose': 'निवडा',
      'start_date': 'प्रारंभ तारीख',
      'end_date': 'शेवटची तारीख',
      'reason': 'कारण',
      'take_photo': 'छायाचित्र घे',
      'submit': 'प्रस्तुत करणे',
      'fill': 'भरा',
      'days': 'दिवस',
      'remark': 'टिप्पणी',
      'reset': 'रीसेट',
      'enter_the_old_password_desc': 'तुमच्या खात्यासह जुना पासवर्ड एंटर करा आणि तुमचा पासवर्ड रीसेट करण्यासाठी जुन्या पासवर्डची पडताळणी करा',
      'old': 'जुन्या',
      'new': 'नवीन',
      'confirm': 'पुष्टी',
      'enter_the': 'प्रविष्ट करा',
      'once_you_start': 'एकदा नवीन सुरुवात करा',
      'you_ll': "तुम्ही कराल",
      'see_it_listen_here': 'ते येथे सूचीबद्ध केलेले पहा',
      'to': 'ते',
      'delete': 'हटवा',
      'this': 'या',
      'edit': 'सुधारणे',
      'is': 'आहे',
      'finished': 'संपले',
      'please_select_valid_date': 'कृपया वैध तारीख निवडा',
      'max': 'कमाल',
      'select': 'निवडा',
      'save': 'जतन करा',
      'updated': 'अपडेट केले',
      'you_can_not': 'आपण आजची समस्या हटवू शकत नाही',
      'first': 'पहिला',
      'enter': 'प्रविष्ट करा',
      'character': 'वर्ण',
      'right': 'बरोबर',
      'same_as': 'च्या सारखे',
      'your_password_changed': 'तुमचा पासवर्ड यशस्वीरित्या बदलला',
      'staff': 'कर्मचारी',
      'overall': 'एकूणच',
      'no_data_found': 'माहिती आढळली नाही',
      'of': 'च्या',
      'site': 'जागा',
      'sites': 'साइट्स',
      'pending': 'प्रलंबित',
      'accept': 'स्वीकारा',
      'reject': 'नाकारणे',
      'data_not_available': 'डेटा उपलब्ध नाही',
      'name': 'नाव',
      'apply_date': 'अर्ज करण्याची तारीख',
      'sub': 'उप',
      'details': 'तपशील',
      'why': 'का',
      'already': 'आधीच',
      'accepted': 'स्वीकारले',
      'rejected': 'नाकारले',
      'status': 'स्थिती',
      'update': 'अपडेट करा',
      'tracking': 'ट्रॅकिंग',
    },
    'hi_IN':{
      'fieldstafftrackingsystem':'फील्ड स्टाफ ट्रैकिंग सिस्टम',
      'login':'लॉग इन करें',
      'username':'उपयोगकर्ता नाम',
      'pleaseenterusername':'कृपया उपयोगकर्ता नाम दर्ज करें',
      'password':'पासवर्ड',
      'pleaseenterpassword':'कृपया पासवर्ड दर्ज करें',
      'forgotpassword':'पासवर्ड भूल गए',
      'technicalsupport':'तकनीकी समर्थन',
      'alert':'चेतावनी',
      'please_wait': 'कृपया प्रतीक्षा करें',
      'success':'सफलता',
      'login_success':'सफलतापूर्वक लॉगिन करें',
      'please_check_internet':'कृपया अपना इंटरनेट जांचें',
      'profile': 'प्रोफ़ाइल',
      'hr_staff_attendance': 'स्टाफ की उपस्थिति',
      'leave_request': 'छुट्टी का अनुरोध',
      'change_language': 'भाषा बदलें',
      'change_password': 'पासवर्ड बदलें',
      'logout': 'लॉग आउट',
      'are_you_sure_want_to': 'क्या आप वाकई चाहते हैं',
      'yes': 'ठीक है',
      'no': 'नहीं',
      'gujarati': 'गुजराती',
      'english': 'अंग्रेज़ी',
      'marathi': 'मराठी',
      'hindi': 'हिंदी',
      'choose_site': 'अपनी साइट चुनें',
      'choose_sub_site': 'अपनी उप साइट चुनें',
      'punch_out_anywhere': 'कहीं से भी मुक्का मारो',
      'please': 'कृपया',
      'punch' : 'मुक्का',
      'in': 'में',
      'out': 'बाहर',
      'attendance': 'उपस्थिति',
      'already_done': 'किया हुआ है',
      'next': 'अगला',
      'or': 'या',
      'after': 'बाद',
      'hrs_left': 'घंटा बाकि',
      'ok': 'ठीक है',
      'successfully': 'सफलतापूर्वक',
      'sorry': 'क्षमा करें',
      'you_are_in_site': 'आप साइट पर हैं',
      'you_are_not_in_site': 'आप साइट पर नहीं हैं',
      'please_go_to_your_site': 'कृपया अपनी साइट पर जाएँ',
      'time': 'समय',
      'working_hrs': 'कार्य के घंटे',
      'no_internet_connection': 'कोई इंटरनेट कनेक्शन नहीं',
      'home': 'घर',
      'map': 'नक्शा',
      'report': 'प्रतिवेदन',
      'leave': 'छुट्टी',
      'track': 'रास्ता',
      'problems': 'समस्या',
      'problem': 'समस्या',
      'its_take_a_time_while_loading_map': "मानचित्र लोड करने में समय लग रहा है",
      'notifications': 'सूचनाएं',
      'record_not_found': 'रिकॉर्ड नहीं मिला',
      'present': 'उपस्थित',
      'absent': 'अनुपस्थित',
      'total': 'कुल',
      'monthly': 'महीने के',
      'numb': 'संख्या',
      'type': 'प्रकार',
      'working_hours': 'कार्य के घंटे',
      'my': 'मेरा',
      'quota': 'कोटा',
      'used': 'उपयोग',
      'available': 'उपलब्ध',
      'add': 'जोड़ना',
      'choose': 'चुनें',
      'start_date': 'आरंभ करने की तिथि',
      'end_date': 'अंतिम तिथि',
      'reason': 'कारण',
      'take_photo': 'फोटो लो',
      'submit': 'जमा करना',
      'fill': 'भरें',
      'days': 'दिन',
      'remark': 'टिप्पणी',
      'reset': 'रीसेट',
      'enter_the_old_password_desc': 'अपने खाते का पुराना पासवर्ड दर्ज करें और अपना पासवर्ड रीसेट करने के लिए पुराना पासवर्ड सत्यापित करें',
      'old': 'पुराना',
      'new': 'नया',
      'confirm': 'पुष्टि कीजिये',
      'enter_the': 'दर्ज करें',
      'once_you_start': 'एक बार जब आप कोई नई शुरुआत करेंगें',
      'you_ll': "तो आप",
      'see_it_listen_here': 'इसे यहां सूचीबद्ध देखें',
      'to': 'से',
      'delete': 'हटाना',
      'this': 'यह',
      'edit': 'संपादित',
      'is': 'है',
      'finished': 'खत्म',
      'please_select_valid_date': 'कृपया वैध तिथि चुनें',
      'max': 'अधिकतम',
      'select': 'चुनें',
      'save': 'सहेजें',
      'updated': 'अद्यतन',
      'you_can_not': 'आप आज की समस्या को मिटा नहीं सकते',
      'first': 'पहिला',
      'enter': 'पदर्ज करें',
      'character': 'चरित्र',
      'right': 'सही',
      'same_as': 'के समान',
      'your_password_changed': 'आपका पासवर्ड सफलतापूर्वक बदल गया',
      'staff': 'कर्मचारी',
      'overall': 'समग्र',
      'no_data_found': 'कोई डेटा नहीं मिला',
      'of': 'से',
      'site': 'साइट',
      'sites': 'साइटों',
      'pending': 'लंबित',
      'accept': 'स्वीकार करें',
      'reject': 'अस्वीकार करें',
      'data_not_available': 'डेटा उपलब्ध नहीं',
      'name': 'नाम',
      'apply_date': 'आवेदन की तिथि',
      'sub': 'उप',
      'details': 'विवरण',
      'why': 'क्यों',
      'already': 'पहले से',
      'accepted': 'स्वीकृत कर दिया',
      'rejected': 'अस्वीकार कर दिया',
      'status': 'स्थिति',
      'update': 'अद्यतन',
      'tracking': 'नज़र रखना',
    },
    'guj_IN':{
      'fieldstafftrackingsystem':'ફિલ્ડ સ્ટાફ ટ્રેકિંગ સિસ્ટમ',
      'login':'પ્રવેશ કરો',
      'username':'વપરાશકર્તા નામ',
      'pleaseenterusername':'કૃપા કરીને વપરાશકર્તા નામ દાખલ કરો',
      'password':'પાસવર્ડ',
      'pleaseenterpassword':'કૃપા કરીને પાસવર્ડ દાખલ કરો',
      'forgotpassword':'પાસવર્ડ ભૂલી ગયા છો',
      'technicalsupport':'ટેકનિકલ સપોર્ટ',
      'alert':'ચેતવણી',
      'please_wait': 'મહેરબાની કરી રાહ જુવો',
      'success':'સફળતા',
      'login_success':'સફળતાપૂર્વક લૉગિન',
      'please_check_internet':'કૃપા કરીને તમારું ઇન્ટરનેટ તપાસો',
      'profile': 'પ્રોફાઇલ',
      'hr_staff_attendance': 'સ્ટાફ હાજરી',
      'leave_request': 'વિનંતી છોડો',
      'change_language': 'ભાષા બદલો',
      'change_password': 'પાસવર્ડ બદલો',
      'logout': 'લૉગ આઉટ',
      'are_you_sure_want_to': 'શું તમે ખરેખર કરવા માંગો છો',
      'yes': 'હા',
      'no': 'ના',
      'gujarati': 'ગુજરાતી',
      'english': 'અંગ્રેજી',
      'marathi': 'મરાઠી',
      'hindi': 'હિન્દી',
      'choose_site': 'તમારી સાઇટ પસંદ કરો',
      'choose_sub_site': 'તમારી સબ સાઇટ પસંદ કરો',
      'punch_out_anywhere': 'ગમે ત્યાંથી બહાર કાઢો',
      'please': 'મહેરબાની કરીને',
      'punch' : 'મુક્કો',
      'in': 'માં',
      'out': 'બહાર',
      'attendance': 'હાજરી',
      'already_done': 'ક્યાર્ની કરી દીધી',
      'next': 'આગામી',
      'or': 'અથવા',
      'after': 'પછી',
      'hrs_left': 'કલાક બાકી',
      'ok': 'બરાબર',
      'successfully': 'સફળતાપૂર્વક',
      'sorry': 'માફ કરશો',
      'you_are_in_site': 'તમે સાઈટમાં છો',
      'you_are_not_in_site': 'તમે સાઈટમાં નથી',
      'please_go_to_your_site': 'કૃપા કરીને તમારી સાઇટ પર જાઓ',
      'time': 'સમય',
      'working_hrs': 'કામ નાં કલાકો',
      'no_internet_connection': 'ઇન્ટરનેટ કનેક્શન નથી',
      'home': 'ઘર',
      'map': 'નકશો',
      'report': 'અહેવાલ',
      'leave': 'રજા',
      'track': 'ટ્રેક',
      'problems': 'સમસ્યાઓ',
      'problem': 'સમસ્યાઓ',
      'its_take_a_time_while_loading_map': "નકશો લોડ કરવામાં થોડો સમય લાગે છે",
      'notifications': 'સૂચનાઓ',
      'record_not_found': 'રેકોર્ડ મળ્યો નથી',
      'present': 'હાજર',
      'absent': 'ગેરહાજર',
      'total': 'કુલ',
      'monthly': 'માસિક',
      'numb': 'સંખ્યા',
      'type': 'પ્રકાર',
      'working_hours': 'કામ નાં કલાકો',
      'my': 'મારા',
      'quota': 'ક્વોટા',
      'used': 'વપરાયેલ',
      'available': 'ઉપલબ્ધ',
      'add': 'ઉમેરો',
      'choose': 'પસંદ કરો',
      'start_date': 'પ્રારંભ તારીખ',
      'end_date': 'અંતિમ તારીખ',
      'reason': 'કારણ',
      'take_photo': 'ફોટો લો',
      'submit': 'સબમિટ કરો',
      'fill': 'ભરો',
      'days': 'દિવસ',
      'remark': 'ટિપ્પણી',
      'reset': 'રીસેટ',
      'enter_the_old_password_desc': 'તમારા એકાઉન્ટ સાથે જૂનો પાસવર્ડ દાખલ કરો અને તમારો પાસવર્ડ રીસેટ કરવા માટે જૂના પાસવર્ડની ચકાસણી કરો',
      'old': 'જુનો',
      'new': 'નવો',
      'confirm': 'પુષ્ટિ કરો',
      'enter_the': 'દાખલ કરો',
      'once_you_start': 'એકવાર તમે નવું શરૂ કરો',
      'you_ll': "તે પછી તમે",
      'see_it_listen_here': 'તેને અહીં સૂચિબદ્ધ જોશો',
      'to': 'થી',
      'delete': 'કાઢી નાખો',
      'this': 'આ',
      'edit': 'સંપાદિત કરો',
      'is': 'છે',
      'finished': 'સમાપ્ત',
      'please_select_valid_date': 'કૃપા કરીને માન્ય તારીખ પસંદ કરો',
      'max': 'મહત્તમ',
      'select': 'પસંદ કરો',
      'save': 'સાચવો',
      'updated': 'અપડેટ કરેલ',
      'you_can_not': "તમે આજની સમસ્યાને કાઢી શકતા નથી",
      'first': 'પ્રથમ',
      'enter': 'દાખલ કરો',
      'character': 'પાત્ર',
      'right': 'અધિકાર',
      'same_as': 'ના જેવું સરખું',
      'your_password_changed': 'તમારો પાસવર્ડ સફળતાપૂર્વક બદલાયો',
      'staff': 'સ્ટાફ',
      'overall': 'એકંદરે',
      'no_data_found': 'કોઈ ડેટા મળ્યો નથી',
      'of': 'માંથી',
      'site': 'સાઇટ',
      'sites': 'સાઇટ્સ',
      'pending': 'અસ્વીકાર કરો',
      'accept': 'સ્વીકાર્યું',
      'reject': 'નામંજૂર',
      'data_not_available': 'ડેટા ઉપલબ્ધ નથી',
      'name': 'નામ',
      'apply_date': 'તારીખ લગુ કરેલ',
      'sub': 'સબ',
      'details': 'વિગતો',
      'why': 'શા માટે',
      'already': 'પહેલેથી જ',
      'accepted': 'સ્વીકાર્યું',
      'rejected': 'નામંજૂર',
      'status': 'સ્થિતિ',
      'update': 'અપડેટ કરો',
      'tracking': 'ટ્રેકિંગ',
    },
  };

}